### ISSUE TITLE
Add `set_tasks_status` method to `AlchemiscaleClient`; only allow setting to `waiting`, `invalid`, `deleted` via API

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#102]
We want users to be able to set a task's status to any one of `waiting`, `invalid`, or `deleted`, as permitted by the storage layer. We need a `set_tasks_status` method on the `AlchemiscaleClient` that does this, with `AlchemiscaleAPI` enforcement that only these statuses are allowed to be set to by a user.

The corresponding `Neo4jStore` methods already enforce what statuses are allowed to transition to `waiting`, `invalid`, or `deleted`, so there will be no need to do any additional enforcement.

**Comment by dotsdl** [comment]
@hmacdope, can you take this on?

**Comment by hmacdope** [comment]
@dotsdl yarp
