### ISSUE TITLE
Feedback on client about how many ProtocolDags formed part of your estimate/uncertainty

### ISSUE THREAD

**Issue by hmacdope** [openforcefield/alchemiscale#105]
**In broad terms, what are you trying to do?**

A user should be warned when they pull down a set of transformation results and not everything is finished.

We need a clear visual and programatic way for users to see whether all their queued work had been finished and taken into account in an estimate or uncertainty.

As part of this we may want to package the "result" of an estimate and uncertainty together in a model so that they can't become decoupled. Im sure the folks over at GUFE may have some elegant solution to this.

**Comment by dotsdl** [comment]
Perhaps we could do the following:

1. Create `AlchemiscaleClient.get_transformation_status(transformation: ScopedKey)`:
- gives a tree view of `Task`s associated with the given `Transformation`
- useful for users in understanding the state of a `Transformation` they are interested in
2. Rename `AlchemiscaleClient.get_tasks` to `AlchemiscaleClient.get_transformation_tasks(transformation: ScopedKey)`:
- gives full list or `networkx.DiGraph` of `Task`s for more programmatic introspection of `Transformation` status

I think this should give users the touchpoints they need to understand compute state.
