### ISSUE TITLE
Compute-side bottleneck when many compute services attempt to claim from a single `TaskHub`

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#121]
First reported [here](https://github.com/openforcefield/alchemiscale/pull/120#issuecomment-1510511650) in #120.

We observe a bottleneck compute-side with task claiming when there are a small number of `TaskHub`s/`AlchemicalNetwork`s with available `Task`s, since the claiming code must currently lock the `TaskHub` while performing claiming. This linearizes requests for new `Task`s from a given `TaskHub` by compute services, causing a bit of starving compute.

This can be mitigated by setting the number of tasks claimed at a time on compute services higher. The problem will also be diminished when many `TaskHub`s have waiting tasks, as well as when tasks take much longer than the ~1min tasks I've been testing with.

Addressing this issue directly will require a more efficient claiming code path. Ideally we would be able to claim `Task`s from a `TaskHub` in a single Cypher query, but this may not be possible given our approach to claiming. Alternative to this, a rework of the claiming code that avoids the need to lock the `TaskHub` being claimed from may also yield higher aggregate performance.

**Comment by dotsdl** [comment]
We're getting bitten by this at the moment on `alchemiscale.org`; a network with ~2400 tasks has them all actioned at the same time, and this appears to be causing for very slow claims going through. It would be worthwhile to address this for the next release.

**Comment by jchodera** [comment]
Is it the slow serialization and transmission of a Task that is the issue?

If so, could you have a lightweight ticket stand-in for a Task (eg a pointer to a Task) and perform the atomic interactions on that, and have a separate service allow multiple workers to claim those tickets to grab serialized copies of the Task in parallel by a service backed with many threads?

**Comment by dotsdl** [comment]
It is unclear as of yet what the exact bottleneck(s) of the claiming code are, in particular its poor scaling with the number of `Task`s actioned at a given moment on a single `TaskHub`.

`Task`s are already very lightweight, and so adding a stand-in wouldn't help us here. Because we do weighted selection partitioned on priority, we need to lock the `TaskHub` during this operation to avoid two requesters claiming the same `Task`.

There are several opportunities to reduce claiming time, including at least:
1. move most of the logic living in `SynchronousComputeService.claim_tasks` into the compute API itself, avoiding many HTTP requests scaling roughly with the number of `AlchemicalNetwork`s visible to the service.
2. avoid use of `to_subgraph()` in the claiming code within `Neo4jStore`, avoiding unnecessary object creation when we get away with operating on record data more directly.
3. remove any unnecessary returns from queries in the claiming code, such as `tasks`, since we select based on the `actions` relationships.
