### ISSUE TITLE
Add packages to conda-forge

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#125]
We cannot easily distribute packages via PyPI due to our heavy dependence on the OpenFF/OpenFE ecosystems, which are reliant on `conda-forge` as the primary/sole distribution channel. We should aim to put `alchemiscale` on `conda-forge` as well.

We'd like this distributed as at least three packages:
- `alchemiscale-server`
- `alchemiscale-compute`
- `alchemiscale-client`

These mirror the corresponding environments we already deploy with.

**Comment by dotsdl** [comment]
@mikemhenry is this a process you're willing to initiate?

**Comment by dotsdl** [comment]
Current dependence on choderalab/perses#1066 is blocking this.

**Comment by mikemhenry** [comment]
Yes I can work on this, even with the blocker, I think it is worth getting a recipe into staged recipes.

**Comment by mikemhenry** [comment]
Working on this!

**Comment by mikemhenry** [comment]
Resolved with https://github.com/conda-forge/staged-recipes/pull/23919

**Comment by mikemhenry** [comment]
Done https://github.com/conda-forge/alchemiscale-feedstock
