### ISSUE TITLE
[ENH] Ability to see summary of task status at org / campaign / project level

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/alchemiscale#126]
As far as I'm aware this isn't available using the client (at least not through the documentation provided to initial users).

It would be great if it would be possible to see the status of all tasks for an org / campaign / project using a single command rather than have to iterate through all the transformations. This would make it easier to track how things are going.

**Comment by hmacdope** [comment]
@dotsdl I can take this one on.

**Comment by dotsdl** [comment]
@hmacdope yes please, if you have bandwidth!

**Comment by ijpulidos** [comment]
Yes, I'm now running ~2400 tasks for the  NEQ cycling protocol and having to deal with them individually is not ideal. +1 for having a way to ask about "anything running/failing/waiting/etc." at higher levels (scope: org, campaign, project) and networks.

**Comment by dotsdl** [comment]
@hmacdope are you able to focus effort on this issue this sprint? Otherwise happy to take it on.

**Comment by hmacdope** [comment]
Probably not this sprint @dotsdl, i'll go ahead and unassign myself.
