### ISSUE TITLE
[ENH] `create_network` can be very slow with complexes

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/alchemiscale#129]
Just adding this here so that other users can be aware of it.

I'm not sure if there's much that can be done here except maybe compressing the payloads being uploaded, but, even for a small set like TYK2, uploading a network including a complex is very slow (5+ minutes on a ~ 20 Mbps upload line).

**Comment by dotsdl** [comment]
I've used the TYK2 set for testing many times, and it took seconds, not minutes. I'm on a 500 Mbps line, however, so perhaps this is the difference?

If network (as in bandwidth) is the bottleneck here, then compression between client and API services may help us here. We have kicked around trying e.g. `msgpack` for this, as an example.

**Comment by IAlibay** [comment]
It's probably a mix of upload bandwidth and also server location?

A quick diagnosis might be to see how bad things are for @hmacdope - if australia doesn't face significant slowdowns then it's unlikely to be a problem?
