### ISSUE TITLE
`get_transformation_status` returns `True` for transformations that don't exist

### ISSUE THREAD

**Issue by ijpulidos** [openforcefield/alchemiscale#131]
As far as I can tell, as long as your organization is valid (this would be `ORGANIZATION` in the following code), running `AlchemiscaleClient.get_transformation_status` method with random scope key returns `True` and seems "successful" even though there is no transformation with that scope key. Example of code as follows:

```python
asc.get_transformation_status("IMadeThisUp-a1s2d3f4g5h6j7k8l9-ORGANIZATION-askdjf-qwerty")

#### This is the output ####
Alchemiscale Task Status for transformation: IMadeThisUp-a1s2d3f4g5h6j7k8l9-ORGANIZATION-askdjf-qwerty

Complete: 0
Waiting:  0
Running:  0
Error:    0
Invalid:  0
Deleted:  0
-----------
Total Complete:  0/0

Transformation complete!
Out[8]: True

```
I don't think this is a major issue, but it can seem confusing for users to get this output when a transformation doesn't exist, and maybe could be generating bigger issues deeper in a workflow if this is not detected early.

**Comment by hmacdope** [comment]
Good point, `get_transformation_status` should probably check if the transformation exists.

**Comment by dotsdl** [comment]
The `AlchemiscaleClient.get_transformation_status` method no longer returns `True`, so this is now resolved.
