### ISSUE TITLE
Ensure that issuing a `KeyboardInterrupt` to a `SynchronousComputeService` does not result in a `ProtocolDAGResult` being pushed

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#132]
It is important that we are able to interrupt `SynchronousComputeService`s at will. If a `Task` is being executed at the time of interruption, a `ProtocolDAGResult` with a `KeyboardInterrupt` should not be pushed, with the `Task` set to `error`. Instead, the `Task` should be set back to `waiting`.

Currently, it appears that either of the two outcomes above can occur. To avoid the `KeyboardInterrupt` being swallowed by the `raise_error=False` logic in `gufe.protocols.protocoldag.execute_DAG`, it may be necessary for `SynchronousComputeService` to feature its own implementation that deals with `KeyboardInterrupt`s as a special case.

**Comment by mikemhenry** [comment]
Is treating `KeyboardInterrupt` as a special case something we would want to upstream as well? It seems like that is something a user would always want to do

**Comment by dotsdl** [comment]
Ah good call @mikemhenry; I'll try the route of upstreaming it first.

**Comment by dotsdl** [comment]
Kicking to 0.2.0 milestone, since this might entirely be a `gufe` issue. If it gets resolved there and we don't see `KeyboardInterrupt`s in failed `ProtocolUnit` tracebacks anymore, we'll close.

**Comment by dotsdl** [comment]
Upstreamed here: https://github.com/OpenFreeEnergy/gufe/pull/215
