### ISSUE TITLE
Various `AlchemiscaleClient` improvements

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#136]
This issue is meant to capture several additions/changes we'd like to make to the `AlchemiscaleClient` given the user experience shared so far. These items could be split into separate issues, or simply addressed via multiple PRs.

Its scope may expand over the course of development for 0.2.0.

1. [ ]  Add a `set_transformation_tasks` method that sets the total number of `Task`s on a `Transformation`; this is intended as an idempotent way to declare the minimum number of `Task`s that should exist on a `Transformation`, including collectively all 'waiting', 'running', 'complete', and 'error'. It will not include `Task`s with statuses outside of theses, such as 'deleted' or 'invalid'. Somewhat complementary to #134.

2. [ ] <strike>Add `return_as` kwarg to `get_transformation_status`; make `bool` the default, but make `dict` another option giving the status counts for the `Transformation` in a `dict`. This would allow for more programmatic status usage if desired.</strike>

3. [ ]  Add in-memory and optionally on-disk caching of `ProtocolDAGResult`s retrieved with the client. These caches could be used to speed up and substantially reduce the number of network retrievals required for calculating results for a `Transformation`.

4. [x] Change `Task` get/set methods to operate in bulk, instead of looping locally through `Task`s.

5. [ ] <strike>Change all API endpoints to use singular entity for individual entity selection and operations; use plural entity for bulk operations.</strike>

6. [x] For `ProtocolDAGResult` retrieval in `_get_protocoldagresults`, perform in an `async` loop for multiple concurrent requests, higher overall performance.

7. [x] Add `get_network_transformations` and `get_network_chemicalsystems` methods for getting all `ScopedKey`s for `Transformation`s and `ChemicalSystem`s in a given network.

8. <strike>[ ] Change all `get_*` methods that return actual `gufe` objects to `retrieve_`; `get_*` methods should be fast and generally give `ScopedKey`s or other lightweight attribute data.</strike>

**Comment by ijpulidos** [comment]
Nice to see we are thinking about this, since we probably need faster access to transformation results. While running the `tyk2` benchmark using the NEQ cycling protocol, I saw that times for retrieving results can vary a lot from `solvent` compared to `complex` transformations as shown in the figure.

![image](https://user-images.githubusercontent.com/2949729/235260569-20d1d277-1c17-4603-b851-905f5e3c297e.png)

The longer times correspond to getting transformation results (using `get_transformation_results`) that come from `complex` transformations/tasks. I hope this is useful information.

**Comment by dotsdl** [comment]
Thanks for this @ijpulidos! 

For clarification: are the times (y-axis) given here the time it took to retrieve a single `ProtocolDAGResult` for each `Transformation` (x-axis), or for all the `ProtocolDAGResult`s in total for each `Transformation`? If the latter, about how many was this?

**Comment by dotsdl** [comment]
From @jscheen: definitely want item (7).

**Comment by dotsdl** [comment]
Closing this one; we've either achieved many of these, articulated them in other issues, or established that they aren't of interest to users. Can resurrect the contents of this issue as more specific issues if needed.
