### ISSUE TITLE
Async or more efficient way of getting the results from a network

### ISSUE THREAD

**Issue by ijpulidos** [openforcefield/alchemiscale#140]
At this moment we need to loop through all the transformations in a network to get the results. Currently this takes a significant amount of time since we have to query for each of them individually. In the same spirit as with https://github.com/openforcefield/alchemiscale/issues/126 (that one is for statuses this one is for results).

We could benefit from having an API point where we can ask for all of the results in an network and obtain them in a single query.

A workaround for this at the moment is to use multiprocessing (or similar) by querying in parallel from different processes or threads.

**Describe the new feature(s) that would help you to achive this**

This will just help analyzing the results from an alchemical network more rapidly and without stressing the API service too much.

**Comment by dotsdl** [comment]
We want to make the `AlchemiscaleClient._get_protocoldagresult` use `async/await` instead of a simple loop to request and deserialize `ProtocolDAGResult`s in the client.

**Comment by dotsdl** [comment]
I'll create an issue as well detailing a design for client caching, which would make repeated calls to grab results much faster and easier on the server-side infrastructure.
