### ISSUE TITLE
Installation v0.1.4

### ISSUE THREAD

**Issue by hannahbaumann** [openforcefield/alchemiscale#164]
I followed these install instruction to install the newest version:
git clone https://github.com/openforcefield/alchemiscale.git
cd alchemiscale
git checkout v0.1.4

mamba env create -f devtools/conda-envs/alchemiscale-client.yml

However, after installation conda list still showed that v0.1.3 was installed. When I looked into the alchemiscale-client.yml file I saw that it installs alchemiscale from
- git+https://github.com/openforcefield/alchemiscale.git@v0.1.3

**Comment by dotsdl** [comment]
Apologies @hannahbaumann, I failed to update those files as part of the process for deployment last night. We'll get this fixed immediately.
