### ISSUE TITLE
Ability to set `weight` on a per-`Task` basis?

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#23]
Perhaps in addition to `priority`, setting a `weight` on a `Task` for a given `Transformation` could be used to encode the difficulty of the `Transformation` (e.g. how much sampling is required to get a converged result). This would help with resource allocation. 

Under this scheme, `priority` would function as a partitioning scheme, with `Task`s of equal priority selected based on their `weight`. It's also worth considering if `priority` should be deprecated in favor of `weight` to avoid too much complexity here. This would be a simplification, making `weight` the only sole selection scheme at both the `TaskQueue` and `Task` level.

**Comment by dotsdl** [comment]
Instead of having `TaskQueue`s, we could switch to each `AlchemicalNetwork` having a `TaskHub`. `Task`s would then be associated with the `TaskHub`, and the connecting edge could feature a `weight` property. `Task`s would then be drawn from a `TaskHub` based on their weight, just as `TaskHub`s themselves are.

This would ditch determinism or any sense of order for `Task`s in terms of execution. We could perhaps retain `priority` as a `Task` property that takes precedence over `weight` considerations (`Task`s of equal, highest priority for a `TaskHub` would be selected for compute based on weight). We could also consider a `tag` property for `Task`s that would allow compute services to filter for only `Task`s with a given set of tags.

**Comment by dotsdl** [comment]
@jchodera do you have a preference. @dwhswenson, @richardjgowers any thoughts on this?

**Comment by dotsdl** [comment]
I need to check if Cypher exposes any random choice functions so we can do our weighted selection and claiming of `Task`s in a single transaction.

**Comment by jchodera** [comment]
I very much support the idea of using _weights_ (rather than _priorities_) for both `Task` and `TaskHub`. This enables the execution engine to be more relaxed in how it uses these weights to stochastically prioritize effort, ensures we don't have to worry about enforcing strict priorities, and will support adaptive weight updating strategies that are only weakly coupled to the execution engine.

**Comment by dotsdl** [comment]
Adding this to release 0.2.0; we'll proceed with `TaskQueue`s for now for 0.1.0, but switch to `TaskHub`s shortly after. 

There does not appear to be a way to directly do a weighted random choice in Cypher, nor do a cumulative sum to implement one in a query. So we may have to resort to doing the weighted selection in Python within the compute API's `Neo4jStore`. I believe we can make this happen within a single transaction even if it isn't all in a single query.

**Comment by jchodera** [comment]
I wonder if there is a simple way to do this with [`rand()`](https://stackoverflow.com/questions/57014583/neo4j-cypher-randomly-match-nodes) using a two-pass approach:
1. Retrieve all the nodes that match the desired criteria and sum up their `weight`s
2. Make another query using a `rand()` selection designed to return everything where `rand() <= weight * number_of_nodes_desired / weight_sum`, which should produce approximately `number_of_nodes_desired` results

**Comment by hmacdope** [comment]
@dotsdl and I have decided to split this into two seperate issues. Redesigning the `TaskQueue` system to use `TaskHubs` is now in issue #78
while adding "compute tags" that allow tasks to be called by some kind of identifier is now in issue #79

**Comment by hmacdope** [comment]
This was mostly addressed by #80. Now that we have a seperate issue for "tags" in #79  I am going to go ahead and close @dotsdl. Feel free to re-open if you want.
