### ISSUE TITLE
Deployment : `docker-compose` deployment of full stack on single host

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#25]
We would like a `docker-compose.yml` hosted in this repo that allows for relatively easy deployment of all service components on a single host. The services it needs include:
- [x] `neo4j` : database with a named, persistent volume; must be initialized on creation
- [x] `FahAlchemyAPI` : Gunicorn + uvicorn serving FastAPI instance; requires DB credentials via env variables
- [x] `FahAlchemyComputeAPI` : Gunicorn + uvicorn serving FastAPI instance; requires DB credentials via env variables
- [x] `traefik` : TLS termination proxy for both API services; should be configurable for Let's Encrypt cert rotation, or an existing cert

Ideally this makes configuration of a `fah-alchemy` Folding@Home work server a two-step process, where the first step is setting up the work server itself, and the second step is standing up these services with `docker-compose`.

**Comment by mikemhenry** [comment]
@dotsdl is `fah-alchemy database init` safe to run more than once? It looks safe
```python

  79     def initialize(self):
  80         """Initialize database.
  81
  82         Ensures that constraints and any other required structures are in place.
  83         Should be used on any Neo4j database prior to use for fah-alchemy.
  84
  85         """
  86         for label, values in self.constraints.items():
  87             self.graph.run(
  88                 f"""
  89                 CREATE CONSTRAINT {values['name']} IF NOT EXISTS
  90                 FOR (n:{label}) REQUIRE n.{values['property']} is unique
  91             """
  92             )
  93
  94         # make sure we don't get objects with id 0 by creating at least one
  95         # this is a compensating control for a bug in py2neo, where nodes with id 0 are not properly
  96         # deduplicated by Subgraph set operations, which we currently rely on
  97         # see this PR: https://github.com/py2neo-org/py2neo/pull/951
  98         self.graph.run("MERGE (:NOPE)")
```

**Comment by mikemhenry** [comment]
Also given #38 what commands need to run for `FahAlchemyClientAPI` and `FahAlchemyComputeAPI`?

**Comment by dotsdl** [comment]
> @dotsdl is `fah-alchemy database init` safe to run more than once? It looks safe
> 
> ```python
>   79     def initialize(self):
>   80         """Initialize database.
>   81
>   82         Ensures that constraints and any other required structures are in place.
>   83         Should be used on any Neo4j database prior to use for fah-alchemy.
>   84
>   85         """
>   86         for label, values in self.constraints.items():
>   87             self.graph.run(
>   88                 f"""
>   89                 CREATE CONSTRAINT {values['name']} IF NOT EXISTS
>   90                 FOR (n:{label}) REQUIRE n.{values['property']} is unique
>   91             """
>   92             )
>   93
>   94         # make sure we don't get objects with id 0 by creating at least one
>   95         # this is a compensating control for a bug in py2neo, where nodes with id 0 are not properly
>   96         # deduplicated by Subgraph set operations, which we currently rely on
>   97         # see this PR: https://github.com/py2neo-org/py2neo/pull/951
>   98         self.graph.run("MERGE (:NOPE)")
> ```
> 
> And by more than once, is there a negative consequence to running `init` on a db full of production data?

Yup! It's idempotent. :grin:

**Comment by dotsdl** [comment]
To start the `FahAlchemyAPI` (the user-facing API), the CLI command is e.g.:

```
fah-alchemy api --host 127.0.0.1 --port 8080 --workers 2
```

To start the `FahAlchemyComputeAPI`, the CLI command is e.g.:

```
fah-alchemy compute api --host 127.0.0.1 --port 8080 --workers 2
```

**Comment by dotsdl** [comment]
Key thing: you'll want to inject things like [state (neo4j) and object (s3) store credentials](https://github.com/openforcefield/fah-alchemy/blob/a72cb90336a00360756e4025af672e42983f785d/fah_alchemy/settings.py#L12-L50) as environment variables to the API services.

**Comment by dotsdl** [comment]
@mikemhenry feel free to swap in `nginx` for `traefik` if you judge it to be easier.

**Comment by dotsdl** [comment]
For reference as well, we're using the gunicorn+uvicorn approach for API deployment via our CLI: https://fastapi.tiangolo.com/deployment/server-workers/

This may have implications for TLS termination proxy choices.
