### ISSUE TITLE
Create CLI points for adding, removing, and listing authorized `Scope`s for a given identity

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#69]
We can now add, remove, and list identities via `fah-alchemy identity add|remove|list`, but we also need to be able to add, remove, and list `Scope`s that a given identity can interact with.

There are currently stubs for each of these CLI points, but they need implementations.

**Comment by dotsdl** [comment]
@hmacdope since you recently added the `identity` CLI points, would you be willing to add these methods? This will require adding corresponding methods into `Neo4jStore` as well.

**Comment by hmacdope** [comment]
Yep for sure!
