### ISSUE TITLE
Doc updates following rename to `Alchemiscale`

### ISSUE THREAD

**Issue by hmacdope** [openforcefield/alchemiscale#73]
We need to update the frontmatter in the docs, to have the correct labels now that we have renamed the package to `alchemiscale`

@mikemhenry also wanted to add some url pathing to the docs for an `alchemiscale.org` url (hopefully I got that right)? We can change the deployment url as well if that I easier.

**Comment by mikemhenry** [comment]
Fixed badge here: https://github.com/openforcefield/alchemiscale/pull/74

**Comment by hmacdope** [comment]
This will be closed by #77

**Comment by hmacdope** [comment]
Done
