### ISSUE TITLE
Add `list_scopes` method to `AlchemiscaleClient`

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#83]
Users should be able to interrogate what scopes they have access to via the `AlchemiscaleClient. We would like a `list_scopes` method on the client that returns the contents of their user identity's `scopes` list.

**Comment by dotsdl** [comment]
@hmacdope can you knock this one out?

**Comment by dotsdl** [comment]
Not critical for 0.1.0; adding to 0.2.0.

**Comment by hmacdope** [comment]
Yep of course

**Comment by dotsdl** [comment]
Danke!
