### ISSUE TITLE
Design Task status lifecycle; implement

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#85]
@hmacdope and I worked out a proposed status lifecycle for tasks, with the following statuses:
- `waiting` : default status on creation; eligible for claiming if actioned on a `TaskHub`
- `running` : status once claimed; indicates task is being executed by a compute service; only `waiting` tasks can become `running` tasks; `running` tasks can be returned to `waiting` by the compute service that claimed them (such as on shutdown) or by the `ComputeAPIService` via heartbeat expiration
- `complete` : once executed and with `ProtocolDAGResult.ok() == True`, indicates the task is complete; cannot be returned to `waiting`
- `error` : once executed and with `ProtocolDAGResult.ok() == False`, indicates task has errored; can be returned to `waiting` to be re-run
- `invalid` : used to mark a task as being flawed in some way without "deletion"; marked by user, can be reached from any other status; an `invalid` task cannot be set to any other status thereafter
- `deleted` : used to "delete" a task; marked by user, can be reached from any other status; a `deleted` task cannot be set to any other status thereafter

Additional notes:
1. If a compute service finishes a Task, but its status has been set to anything other than 'running', then the service will not set the status at all.

2. Only `running` Tasks should have CLAIMS relationship (see (3) below).

3. Consider a CLAIMS relationship to a ComputeServiceIdentity node from a Task that is claimed instead of `claim` property

4. Currently, `invalid` and `deleted` statuses cannot be undone; or rather, the model still allows it, but we don't expose a way to do this.

5. Task "ACTIONS" relationships are independent of status; however, only `waiting` tasks that do not "EXTENDS" a non `complete` Task can be claimed.

6. We will consider removing all "ACTIONS" relationships from a Task that is marked `complete`, `invalid`, or `deleted`; the latter two are terminal statuses, while `complete` can only become one of `invalid` or `deleted`; none of these can return to `waiting`. This will declutter TaskHub relationships; there is little reason to keep them once these statuses are reached.

7. It should not be possible to create a Task that `EXTENDS` an `invalid` or `deleted` Task; there is little harm in allowing it, but little reason to either

8. If a Task is marked either `invalid` or `deleted`, then any Task **that EXTENDS it** is recursively marked with that status as well.

See attached diagram for these and other details.

![alchemiscale - task lifecycle drawio(1)](https://user-images.githubusercontent.com/1326811/218663410-ec7516e2-96ca-4ed5-8b5a-baa538999c36.png)

**Comment by dotsdl** [comment]
@hmacdope would you be willing to start up work on this one? We can tag-team it if you want; I'm happy to take on the heartbeat implementation bits, for example.

**Comment by hmacdope** [comment]
> @hmacdope would you be willing to start up work on this one? We can tag-team it if you want; I'm happy to take on the heartbeat implementation bits, for example.

Absolutely :)

**Comment by dotsdl** [comment]
Awesome! Thank you!
