### ISSUE TITLE
GUFE changes broke our tests

### ISSUE THREAD

**Issue by mikemhenry** [openforcefield/alchemiscale#96]
It looks like our CI stopped working
https://github.com/openforcefield/alchemiscale/actions?query=event%3Aschedule
example of one of the failures (I didn't realize we were using gufe test components) 
https://github.com/openforcefield/alchemiscale/actions/runs/4279796814/jobs/7450867072#step:7:674

**Comment by dotsdl** [comment]
I'm working on getting our use of `DummyProtocol` and `BrokenProtocol` in line with latest `gufe`. However, this requires we figure out a way to serialize `Settings` into our Neo4j representation.

@mikemhenry I could use your help with determining the best way to go about this for roundtripping `Settings` objects, especially when they have a custom subclass for `Settings.protocol_settings`.

**Comment by dotsdl** [comment]
Closed by #97
